version: '3'
services: 
    backend:
        restart: on-failure
        tty: true
        #stdin_open: true
        build: 
            context: .
            dockerfile: Dockerfile
        depends_on: 
            - db    
        ports: 
            - "3040:3040"
        volumes: 
            - /app/node_modules
            - .:/app
        command: ["npm","start"]   
    db:
        image: mongo
        ports: 
            - "27017:27017"