version: '3'
services: 
    backend:
        restart: on-failure
        tty: true
        #stdin_open: true
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - "3000:3040"
        depends_on: 
            - db
        command: ["npm","start"]   

    db:
        image: mongo
        ports:
            - "27017:27017"
        command: --serviceExecutor adaptive
        